
#define JSTD_LIB_TO_STRING(x)    #x

#define JSTD_LIB_MAJOR_VERSION   1
#define JSTD_LIB_MINOR_VERSION   0
#define JSTD_LIB_PATCH_VERSION   0

#define JSTD_LIB_VERSION \
    JSTD_LIB_TO_STRING(JSTD_LIB_MAJOR_VERSION) "." \
    JSTD_LIB_TO_STRING(JSTD_LIB_MINOR_VERSION) "." \
    JSTD_LIB_TO_STRING(JSTD_LIB_PATCH_VERSION)
